# SwiftLint Configuration for Food Scanner App

swift_version: 6.2

included:
  - "Food Scanner"
  - "FoodScannerTests"
  - "FoodScannerUITests"

excluded:
  - "Food Scanner/Resources"
  - "Food Scanner/Config"
  - "DerivedData"
  - ".build"
  - "**/*.generated.swift"

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - todo

analyzer_rules:
  - unused_import

# Rule configs
force_unwrapping:
  severity: warning

todo:
  severity: warning

# Match SwiftFormat's `--trailingcommas always`
trailing_comma:
  mandatory_comma: true
  severity: warning
