included:
  - "Food Scanner"
  - "FoodScannerTests"
  - "FoodScannerUITests"

excluded:
  - "Food Scanner/Resources"
  - "Food Scanner/Config"
  - "DerivedData"
  - ".build"
  - "**/*.generated.swift"

disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call

opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - todo
  - unused_closure_parameter
  - unused_optional_binding
  - redundant_nil_coalescing
  - implicit_optional_initialization
  - redundant_type_annotation
  - redundant_void_return
  - single_test_class
  - sorted_first_last
  - switch_case_on_newline
  - toggle_bool
  - trailing_comma
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces

analyzer_rules:
  - unused_import

# Rule configs
force_unwrapping:
  severity: warning

todo:
  severity: warning

trailing_comma:
  mandatory_comma: false
