# SwiftLint Configuration for Food Scanner App

# Paths to include/exclude
included:
  - "Food Scanner"
  - "FoodScannerTests"
  - "FoodScannerUITests"

excluded:
  - "Food Scanner/Resources"
  - "Food Scanner/Config"
  - "DerivedData"
  - ".build"

# Rules to disable (adjust based on your preferences)
disabled_rules:
  - trailing_whitespace
  - line_length
  - function_body_length
  - file_length
  - type_body_length

# Rules to enable
opt_in_rules:
  - empty_count
  - empty_string
  - force_unwrapping
  - implicitly_unwrapped_optional
  - todo
  - unused_import

# Configuration
line_length:
  warning: 120
  error: 150

function_body_length:
  warning: 50
  error: 100

file_length:
  warning: 500
  error: 1000

type_body_length:
  warning: 300
  error: 500

# Allow force unwrapping in specific cases
force_unwrapping:
  severity: warning

# Allow TODO comments but flag them
todo:
  severity: warning
