name: CI
on:
  pull_request: { branches: [ main ] }
  push: { branches: [ main ] }

jobs:
  build-test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      # If you need a specific Xcode, uncomment:
      # - uses: maxim-lobanov/setup-xcode@v1
      #   with: { xcode-version: '16.2' }

      - name: Cache DerivedData & SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/Library/Developer/Xcode/DerivedData
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-dd-${{ hashFiles('**/Package.resolved') }}

      - name: List schemes (debug aid)
        run: xcodebuild -list

      - name: Build & Test (strict)
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -enableCodeCoverage YES \
            test | xcpretty
        shell: bash

  lint:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: SwiftFormat (check)
        run: swift format --recursive --strict .
      - name: SwiftLint (strict)
        run: swiftlint --strict

  codeql:
    runs-on: macos-latest
    permissions:
      security-events: write
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4
      - uses: github/codeql-action/init@v3
        with: { languages: swift }
      - uses: github/codeql-action/analyze@v3

  guards:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail on TODO/FIXME
        run: |
          if grep -RIn --exclude-dir=.build --exclude-dir=DerivedData -E 'TODO|FIXME' Sources Tests; then
            echo "::error::Found TODO/FIXME. Please resolve or annotate."; exit 1; fi
      - name: Ban legacy APIs
        run: |
          if grep -RIn -E 'UIWebView|NSURLConnection' Sources; then
            echo "::error::Legacy API detected."; exit 1; fi
