name: Nightly — Full Tests & Coverage & Live API Smoke

on:
  schedule:
    - cron: '18 7 * * *'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      FDC_API_KEY: ${{ secrets.FDC_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode 26
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.0'

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: ${{ runner.os }}-dd-${{ hashFiles('**/Package.resolved', '**/*.xctestplan', '**/*.pbxproj', '**/*.xcscheme', '**/*.xcconfig') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-dd-

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -scheme "Food Scanner"

      - name: Preboot iPhone 16 simulator
        run: |
          xcrun simctl boot "iPhone 16" || true
          xcrun simctl bootstatus "iPhone 16" -b
          echo "DEST_ID=$(xcrun simctl list devices | awk -F '[()]' '/iPhone 16 .*Booted/{print $2; exit}')" >> $GITHUB_ENV

      # ---------- Unit tests first (fast, with coverage) ----------
      - name: Unit tests (coverage)
        timeout-minutes: 12
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:FoodScannerTests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_PREVIEWS=NO \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -disableAutomaticPackageResolution \
            test | xcpretty

      # ---------- Pre-grant privacy to avoid UI permission alerts ----------
      - name: Grant sim privacy permissions to app (camera/photos/microphone/notifications)
        run: |
          set -eo pipefail
          BUNDLE_ID=$(xcodebuild -scheme "Food Scanner" -showBuildSettings -json \
            | plutil -extract 0.buildSettings.PRODUCT_BUNDLE_IDENTIFIER raw - 2>/dev/null)
          echo "BundleID: $BUNDLE_ID"
          xcrun simctl privacy "$DEST_ID" grant camera "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant photos "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant microphone "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant notifications "$BUNDLE_ID" || true

      # ---------- UI tests second (serial; tighter timeout) ----------
      - name: UI tests (serial)
        timeout-minutes: 20
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:FoodScannerUITests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_PREVIEWS=NO \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -disableAutomaticPackageResolution \
            -parallel-testing-enabled NO \
            test | xcpretty

      # ---------- Live API smoke (kept tiny; skip if no key) ----------
      - name: Live API smoke (skips if no key)
        if: env.FDC_API_KEY != ''
        timeout-minutes: 8
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:IntegrationTests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            test | xcpretty
