name: Nightly — Full Tests & Coverage & Live API Smoke

on:
  schedule:
    - cron: '18 7 * * *'   # 07:18 UTC daily
  workflow_dispatch:

# Avoid overlapping nightlies
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      FDC_API_KEY: ${{ secrets.FDC_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode 26
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.0'

      - name: Init Xcode once
        run: xcodebuild -runFirstLaunch || true

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: ${{ runner.os }}-dd-${{ hashFiles('**/Package.resolved', '**/*.xctestplan', '**/*.pbxproj', '**/*.xcscheme', '**/*.xcconfig') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-dd-

      - name: Preboot iOS 26 (create fresh iPhone 16 on iOS-26 only)
        id: preboot
        shell: bash
        run: |
          set -euo pipefail
          xcrun simctl shutdown all || true

          RUNTIME=$(xcrun simctl list runtimes | sed -n 's/.*- \(com\.apple\.CoreSimulator\.SimRuntime\.iOS-26[-.0-9]*\) (available).*/\1/p' | head -n1)
          if [ -z "$RUNTIME" ]; then
            echo "::error::No iOS 26 simulator runtime available on this runner."
            xcrun simctl list runtimes
            exit 1
          fi
          echo "Using runtime: $RUNTIME"

          NAME="Nightly-iPhone-16-$(date +%s)"
          UDID=$(xcrun simctl create "$NAME" "iPhone 16" "$RUNTIME")
          echo "Created device: $UDID"

          boot_try () { xcrun simctl boot "$1" || true; xcrun simctl bootstatus "$1" -b -t 120; }
          if ! boot_try "$UDID"; then
            echo "Boot timed out. Erasing and retrying…"
            xcrun simctl shutdown "$UDID" || true
            xcrun simctl erase "$UDID" || true
            boot_try "$UDID" || { echo "::error::Simulator failed to boot after retry."; xcrun simctl list devices; exit 1; }
          fi

          echo "DEST_ID=$UDID" >> "$GITHUB_ENV"

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -scheme "Food Scanner"

      # ---------- Unit tests first (fast, with coverage) ----------
      - name: Unit tests (coverage)
        timeout-minutes: 14
        shell: bash
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:FoodScannerTests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_PREVIEWS=NO \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -disableAutomaticPackageResolution \
            test | xcpretty

      # ---------- Pre-grant privacy to avoid permission pop-ups ----------
      - name: Grant sim privacy permissions to app (camera/photos/mic/notifications)
        shell: bash
        run: |
          set -eo pipefail
          BUNDLE_ID=$(xcodebuild -scheme "Food Scanner" -showBuildSettings -json \
            | plutil -extract 0.buildSettings.PRODUCT_BUNDLE_IDENTIFIER raw - 2>/dev/null)
          echo "BundleID: $BUNDLE_ID"
          xcrun simctl privacy "$DEST_ID" grant camera "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant photos "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant microphone "$BUNDLE_ID" || true
          xcrun simctl privacy "$DEST_ID" grant notifications "$BUNDLE_ID" || true

      # ---------- UI tests second (serial; iOS 26 sim) ----------
      - name: UI tests (serial)
        timeout-minutes: 18
        shell: bash
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:FoodScannerUITests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            ENABLE_PREVIEWS=NO \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -disableAutomaticPackageResolution \
            -parallel-testing-enabled NO \
            test | xcpretty

      # ---------- Live API smoke (tiny; skip if no key) ----------
      - name: Live API smoke (skips if no key)
        if: env.FDC_API_KEY != ''
        timeout-minutes: 8
        shell: bash
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -only-testing:IntegrationTests \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            CODE_SIGNING_ALLOWED=NO \
            test | xcpretty
