name: Nightly — Full Tests & Coverage & Live API Smoke

on:
  schedule:
    - cron: '18 7 * * *'   # 07:18 UTC daily
  workflow_dispatch:

# Avoid overlapping nightly runs
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  nightly:
    runs-on: macos-latest
    timeout-minutes: 45
    env:
      FDC_API_KEY: ${{ secrets.FDC_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Xcode 26
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '26.0.0'

      - name: Cache SPM
        uses: actions/cache@v4
        with:
          path: |
            ~/.swiftpm
            ~/Library/Caches/org.swift.swiftpm
          key: ${{ runner.os }}-spm-${{ hashFiles('**/Package.resolved') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-spm-

      - name: Cache DerivedData
        uses: actions/cache@v4
        with:
          path: ./DerivedData
          key: ${{ runner.os }}-dd-${{ hashFiles('**/Package.resolved', '**/*.xctestplan', '**/*.pbxproj', '**/*.xcscheme', '**/*.xcconfig') }}-xcode-26.0
          restore-keys: |
            ${{ runner.os }}-dd-

      - name: Resolve packages
        run: xcodebuild -resolvePackageDependencies -scheme "Food Scanner"

      - name: Preboot iPhone 16 simulator
        run: |
          xcrun simctl boot "iPhone 16" || true
          xcrun simctl bootstatus "iPhone 16" -b
          DEST_ID=$(xcrun simctl list devices | awk -F '[()]' '/iPhone 16 .*Booted/{print $2; exit}')
          echo "DEST_ID=$DEST_ID" >> $GITHUB_ENV

      - name: Build & All Tests (with coverage; includes UI tests)
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            -enableCodeCoverage YES \
            CODE_SIGNING_ALLOWED=NO \
            SWIFT_STRICT_CONCURRENCY=complete \
            OTHER_SWIFT_FLAGS='-warnings-as-errors' \
            -skipPackagePluginValidation \
            -skipMacroValidation \
            -disableAutomaticPackageResolution \
            -parallel-testing-enabled YES \
            test | xcpretty
        shell: bash

      - name: Live API smoke (skips if no key)
        if: env.FDC_API_KEY != ''
        run: |
          set -eo pipefail
          xcodebuild \
            -scheme "Food Scanner" \
            -testPlan "FoodScanner-Full" \
            -destination "id=$DEST_ID" \
            -destination-timeout 60 \
            -derivedDataPath ./DerivedData \
            -only-testing:IntegrationTests \
            CODE_SIGNING_ALLOWED=NO \
            test | xcpretty
